import type { ComponentRegistry } from '../types.js';
import { absolute } from './absolute.js';
import { adder } from './adder.js';
import { andGate } from './and.js';
import { bitAdder } from './bit-adder.js';
import { bitExtender } from './bit-extender.js';
import { bitFinder } from './bit-finder.js';
import { bitSelector } from './bit-selector.js';
import { bufferGate } from './buffer.js';
import { button } from './button.js';
import { clockSource } from './clock.js';
import { comparator } from './comparator.js';
import { constantSource } from './constant.js';
import { controlledBuffer } from './controlled-buffer.js';
import { controlledInverter } from './controlled-inverter.js';
import { counter } from './counter.js';
import { dFlipFlop } from './d-flipflop.js';
import { decoder } from './decoder.js';
import { demux } from './demux.js';
import { divider } from './divider.js';
import { evenParity } from './even-parity.js';
import { exponentiator } from './exponentiator.js';
import { ground } from './ground.js';
import { inputPin } from './input.js';
import { jkFlipFlop } from './jk-flipflop.js';
import { led } from './led.js';
import { minMax } from './min-max.js';
import { multiplier } from './multiplier.js';
import { muxGate } from './mux.js';
import { nandGate } from './nand.js';
import { negator } from './negator.js';
import { norGate } from './nor.js';
import { notGate } from './not.js';
import { oddParity } from './odd-parity.js';
import { orGate } from './or.js';
import { outputPin } from './output.js';
import { por } from './por.js';
import { power } from './power.js';
import { priorityEncoder } from './priority-encoder.js';
import { probe } from './probe.js';
import { pullResistor } from './pull-resistor.js';
import { ram } from './ram.js';
import { registerComponent } from './register.js';
import { rom } from './rom.js';
import { sevenSegment } from './seven-segment.js';
import { shifter } from './shifter.js';
import { shiftRegister } from './shift-register.js';
import { splitter } from './splitter.js';
import { squareRoot } from './square-root.js';
import { srFlipFlop } from './sr-flipflop.js';
import { subtractor } from './subtractor.js';
import { tFlipFlop } from './t-flipflop.js';
import { tunnel } from './tunnel.js';
import { xnorGate } from './xnor.js';
import { xorGate } from './xor.js';

export { absolute } from './absolute.js';
export { adder } from './adder.js';
export { andGate } from './and.js';
export { bitAdder } from './bit-adder.js';
export { bitExtender } from './bit-extender.js';
export { bitFinder } from './bit-finder.js';
export { bitSelector } from './bit-selector.js';
export { bufferGate } from './buffer.js';
export { button, type ButtonState } from './button.js';
export { clockSource, type ClockState } from './clock.js';
export { comparator } from './comparator.js';
export { constantSource } from './constant.js';
export { controlledBuffer } from './controlled-buffer.js';
export { controlledInverter } from './controlled-inverter.js';
export { counter, type CounterState } from './counter.js';
export { dFlipFlop, type DFlipFlopState } from './d-flipflop.js';
export { decoder } from './decoder.js';
export { demux } from './demux.js';
export { divider } from './divider.js';
export { evenParity } from './even-parity.js';
export { exponentiator } from './exponentiator.js';
export { ground } from './ground.js';
export { inputPin, type InputState } from './input.js';
export { jkFlipFlop, type JkFlipFlopState } from './jk-flipflop.js';
export { led } from './led.js';
export { minMax } from './min-max.js';
export { multiplier } from './multiplier.js';
export { muxGate } from './mux.js';
export { nandGate } from './nand.js';
export { negator } from './negator.js';
export { norGate } from './nor.js';
export { notGate } from './not.js';
export { oddParity } from './odd-parity.js';
export { orGate } from './or.js';
export { outputPin } from './output.js';
export { por, type PorState } from './por.js';
export { power } from './power.js';
export { priorityEncoder } from './priority-encoder.js';
export { probe } from './probe.js';
export { pullResistor } from './pull-resistor.js';
export { ram, type RamState } from './ram.js';
export { registerComponent, type RegisterState } from './register.js';
export { rom } from './rom.js';
export { sevenSegment } from './seven-segment.js';
export { shifter } from './shifter.js';
export { shiftRegister, type ShiftRegisterState } from './shift-register.js';
export { splitter } from './splitter.js';
export { squareRoot } from './square-root.js';
export { srFlipFlop, type SrFlipFlopState } from './sr-flipflop.js';
export { subtractor } from './subtractor.js';
export { tFlipFlop, type TFlipFlopState } from './t-flipflop.js';
export { tunnel } from './tunnel.js';
export { xnorGate } from './xnor.js';
export { xorGate } from './xor.js';

/** Register every built-in primitive on the given registry. */
export function registerPrimitives(registry: ComponentRegistry): void {
  // Gates
  registry.register(andGate);
  registry.register(orGate);
  registry.register(notGate);
  registry.register(xorGate);
  registry.register(nandGate);
  registry.register(norGate);
  registry.register(xnorGate);
  registry.register(bufferGate);
  registry.register(oddParity);
  registry.register(evenParity);
  registry.register(controlledBuffer);
  registry.register(controlledInverter);

  // Plexers
  registry.register(muxGate);
  registry.register(demux);
  registry.register(decoder);
  registry.register(priorityEncoder);
  registry.register(bitSelector);

  // Arithmetic
  registry.register(adder);
  registry.register(subtractor);
  registry.register(comparator);
  registry.register(multiplier);
  registry.register(divider);
  registry.register(negator);
  registry.register(absolute);
  registry.register(minMax);
  registry.register(shifter);
  registry.register(bitAdder);
  registry.register(bitFinder);
  registry.register(exponentiator);
  registry.register(squareRoot);

  // Memory / sequential
  registry.register(registerComponent);
  registry.register(counter);
  registry.register(shiftRegister);
  registry.register(ram);
  registry.register(rom);
  registry.register(dFlipFlop);
  registry.register(tFlipFlop);
  registry.register(jkFlipFlop);
  registry.register(srFlipFlop);

  // Wiring / sources
  registry.register(inputPin);
  registry.register(outputPin);
  registry.register(constantSource);
  registry.register(clockSource);
  registry.register(splitter);
  registry.register(tunnel);
  registry.register(power);
  registry.register(ground);
  registry.register(probe);
  registry.register(bitExtender);
  registry.register(pullResistor);
  registry.register(por);

  // I/O peripherals
  registry.register(button);
  registry.register(led);
  registry.register(sevenSegment);
}
